services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./PSQL/postgres-data:/var/lib/postgresql/data
      - ./PSQL/init.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      - "5432:5432"
    restart: "no"

      #  pgadmin:
      #    container_name: pgadmin
      #    image: dpage/pgadmin4:latest
      #    environment:
      #      - PGADMIN_DEFAULT_EMAIL=${MAIL}
      #      - PGADMIN_DEFAULT_PASSWORD=${PASSWORD}
      #    ports:
      #      - "5050:80"
